export default {
  LOGIN_DATA: "LOGIN_DATA",
  LOGOUT_USER: "LOGOUT_USER",
  USER_DATA: "USER_DATA",
  REG_DATA_MEMBER: "REG_DATA_MEMBER",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  REG_DATA_MEMBER_DETAIL: "REG_DATA_MEMBER_DETAIL",
};
